name: mlproject-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.13
  - pip
  - pip:
      - pandas
      - numpy
      - scikit-learn
      - mlflow
      - xgboost
      - dagshub