name: Preprocessing Balita

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # bisa dijalankan manual

jobs:
  preprocessing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install pandas scikit-learn

      - name: Run Preprocessing Script
        run: python preprocess.py

      - name: Upload Preprocessed Dataset
        uses: actions/upload-artifact@v3
        with:
          name: preprocessed-balita
          path: data_balita_ready.csv
